ifun/ifun/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^polls/', include('polls.urls')),
    url(r'^account/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
]

ifun/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

ifun/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$', views.signup, name='signup'),
]

ifun/polls/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
        


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

ifun/users/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Tailor(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)


class Customer(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

ifun/ifun/views.py
from django.shortcuts import get_object_or_404, render


def home(request):
    return render(request, 'ifun/home.html') 

ifun/polls/views.py
from django.shortcuts import get_object_or_404, render
from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context) 

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

ifun/users/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template.context_processors import csrf
from django.contrib import auth
# Create your views here.


def signin(request):
    c = {}
    c.update(csrf(request))
    if request.method == 'GET':
        return render_to_response('users/signin.html', c)
    else:
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            return HttpResponse('logined')
        else:
            return HttpResponse('invalid')


def signup(request):
    if request.method == 'GET':
        return render(request, 'users/signup.html')
    else:
        return HttpResponse('hello post')

ifun/ifun/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Sergey Pozhilov (GetTemplate.com)">
	
	<title>Ifun</title>
   
	<link rel="shortcut icon" href={% static 'images/favicon.png' %}>
	
	
	<link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
	<link rel="stylesheet" href={% static 'css/font-awesome.min.css' %}>

	<!-- Custom styles for our template -->
	<link rel="stylesheet" href={% static 'css/bootstrap-theme.css' %} media="screen" >
	<link rel="stylesheet" href={% static 'css/main.css' %}>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src={% static 'js/html5shiv.js' %}></script>
	<script src={% static 'js/respond.min.js' %}></script>
	<![endif]-->
</head>

<body class="home">
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="index.html"><img src={% static 'images/logo12.png' %} alt=""> I F U N</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li class="active"><a href="/">首页</a></li>
					<li><a href="about.html">关于</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">更多<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="sidebar-left.html">Left Sidebar</a></li>
							<li class="active"><a href="sidebar-right.html">Right Sidebar</a></li>
						</ul>
					</li>					
					<li><a class="btn" href={%url 'signin'%}>登录 / 注册</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div> 
	<!-- /.navbar -->

	
	{%block content%}
    {%endblock%}
	
	
	
	<!-- Social links. @TODO: replace by link/instructions in template -->
	<section id="social">
		<div class="container">
			<div class="wrapper clearfix">
				<!-- AddThis Button BEGIN -->
				<div class="addthis_toolbox addthis_default_style">
				<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_linkedin_counter"></a>
				<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
				</div>
				<!-- AddThis Button END -->
			</div>
		</div>
	</section>
	<!-- /social links -->


	<footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">
					
					<div class="col-md-3 widget">
						<h3 class="widget-title">Contact</h3>
						<div class="widget-body">
							<p>+234 23 9873237<br>
								<a href="mailto:#">some.email@somewhere.com</a><br>
								<br>
								234 Hidden Pond Road, Ashland City, TN 37015
							</p>	
						</div>
					</div>

					<div class="col-md-3 widget">
						<h3 class="widget-title">Follow me</h3>
						<div class="widget-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								<a href=""><i class="fa fa-dribbble fa-2"></i></a>
								<a href=""><i class="fa fa-github fa-2"></i></a>
								<a href=""><i class="fa fa-facebook fa-2"></i></a>
							</p>	
						</div>
					</div>

					<div class="col-md-6 widget">
						<h3 class="widget-title">Text widget</h3>
						<div class="widget-body">
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, dolores, quibusdam architecto voluptatem amet fugiat nesciunt placeat provident cumque accusamus itaque voluptate modi quidem dolore optio velit hic iusto vero praesentium repellat commodi ad id expedita cupiditate repellendus possimus unde?</p>
							<p>Eius consequatur nihil quibusdam! Laborum, rerum, quis, inventore ipsa autem repellat provident assumenda labore soluta minima alias temporibus facere distinctio quas adipisci nam sunt explicabo officia tenetur at ea quos doloribus dolorum voluptate reprehenderit architecto sint libero illo et hic.</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="#">Home</a> | 
								<a href="about.html">About</a> |
								<a href="sidebar-right.html">Sidebar</a> |
								<a href="contact.html">Contact</a> |
								<b><a href="signup.html">Sign up</a></b>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2014, Your name. Designed by <a href="http://gettemplate.com/" rel="designer">gettemplate</a> 
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

	</footer>	
		
   



	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src={% static 'js/jquery.min.js' %}></script>
	<script src={% static 'js/bootstrap.min.js' %}></script>	
	<script src={% static 'js/headroom.min.js' %}></script>
	<script src={% static 'js/jQuery.headroom.min.js' %}></script>
	<script src={% static 'js/template.js' %}></script>
</body>
</html>

ifun/ifun/templates/ifun/home.html
{%extends "base.html"%}
{%block content%}
<!-- Header -->
	<header id="head">
		<div class="container">
			<div class="row">
				<h1 class="lead">量体裁衣，定制您的魅力</h1>
				<p class="tagline">加入IFUN，寻找您的专属设计师；加入IFUN，让您的设计灵感变现实。</p>
				<p><a class="btn btn-info btn-lg" role="button">开始定制</a> <a class="btn btn-action btn-lg" role="button">成为设计师</a></p>
			</div>
		</div>
	</header>
	<!-- /Header -->

	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">每个人都是独一无二的个体</h2>
		<p class="text-muted">
			服饰应该按照个性差异进行设计生产<br> 
			每个人都拥有属于自己的标准身材和时尚
		</p>
	</div>
	<!-- /Intro-->
	
	<!-- container -->
	

	<!-- /container -->

	<!-- Highlights - jumbotron -->
	<!-- Highlights - jumbotron -->
	<div class="jumbotron top-space">
		<div class="container">
			
			<h3 class="text-center thin">Reasons to use this template</h3>
			
			<div class="row">
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-flash  fa-5"></i>Swift</h4></div>
					<div class="h-body text-center">
						<p>
						abc. abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						 </p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-flash fa-5"></i>Simple</h4></div>
					<div class="h-body text-center">
						<p>abc. abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. </p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-heart fa-5"></i>Smart</h4></div>
					<div class="h-body text-center">
						<p>abc. abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. </p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-phone fa-5"></i>Fashion</h4></div>
					<div class="h-body text-center">
						<p>abc. abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. 
						abc.abc. abc. abc. abc. abc. </p>
					</div>
				</div>
			</div> <!-- /row  -->
		
		</div>
	</div>
	<!--
	<div class="top-space">
		<div class="">
		        <div id="map">	
			<h3 class="text-center thin">全国各个城市和地区</h3>
                         
                        <div class="panel panel-info col-sm-5">
                          <div class="panel-body">
                            <form class="row">
                              <div class="col-sm-8">
                                <input type="text" class="form-control search" placeholder="城市或者地区">
                              </div>
                              <button type="button" class="btn btn-info btn-sm" aria-label="Left Align">Go
                              </button> 
                            </form> 
                          </div> 
                        </div>
                        </div>
		</div>
	</div>
	 -->
<!-- container -->
	<div class="container">

		<h2 class="text-center top-space">Frequently Asked Questions</h2>
		<br>

		<div class="row">
			<div class="col-sm-6">
				<h3>Which code editor would you recommend?</h3>
				<p>I'd highly recommend you <a href="http://www.sublimetext.com/">Sublime Text</a> - a free to try text editor which I'm using daily. Awesome tool!</p>
			</div>
			<div class="col-sm-6">
				<h3>Nice header. Where do I find more images like that one?</h3>
				<p>
					Well, there are thousands of stock art galleries, but personally, 
					I prefer to use photos from these sites: <a href="http://unsplash.com">Unsplash.com</a> 
					and <a href="http://www.flickr.com/creativecommons/by-2.0/tags/">Flickr - Creative Commons</a></p>
			</div>
		</div> <!-- /row -->

		<div class="row">
			<div class="col-sm-6">
				<h3>Can I use it to build a site for my client?</h3>
				<p>
					Yes, you can. You may use this template for any purpose, just don't forget about the <a href="http://creativecommons.org/licenses/by/3.0/">license</a>, 
					which says: "You must give appropriate credit", i.e. you must provide the name of the creator and a link to the original template in your work. 
				</p>
			</div>
			<div class="col-sm-6">
				<h3>Can you customize this template for me?</h3>
				<p>Yes, I can. Please drop me a line to sergey-at-pozhilov.com and describe your needs in details. Please note, my services are not cheap.</p>
			</div>
		</div> <!-- /row -->

		<div class="jumbotron top-space">
			<h4>Dicta, nostrum nemo soluta sapiente sit dolor quae voluptas quidem doloribus recusandae facere magni ullam suscipit sunt atque rerum eaque iusto facilis esse nam veniam incidunt officia perspiciatis at voluptatibus. Libero, aliquid illum possimus numquam fuga.</h4>
     		<p class="text-right"><a class="btn btn-primary btn-large">Learn more »</a></p>
  		</div>

</div>	<!-- /container -->
	
{%endblock%}

ifun/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

ifun/polls/templates/polls/index.html
{%extends "base.html" %}
{%block content%}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{%endblock%}

ifun/users/templates/users/signin.html
{%extends "base.html"%}
{%block content%}
	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">


		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">登录</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">请使用已有账户登录</h3>
							<p class="text-center text-muted">没有账号请先 <a href={%url 'signup'%}>注册</a></p>
							<hr>
							
							<form action={%url 'signin'%} method="post">{% csrf_token %}
								<div class="top-margin">
									<label>用户名<span class="text-danger">*</span></label>
									<input type="text" name=username class="form-control">
								</div>
								<div class="top-margin">
									<label>密码<span class="text-danger">*</span></label>
									<input type="password" name=password class="form-control">
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
										<b><a href="">忘记密码？</a></b>
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">登录</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
{%endblock%}	

ifun/users/templates/users/signup.html
{%extends "base.html"%}
{%block content%}
	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="index.html">Home</a></li>
			<li class="active">Registration</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Registration</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Register a new account</h3>
							<p class="text-center text-muted">Lorem ipsum dolor sit amet, <a href={%url 'signin'%}>Login</a> adipisicing elit. Quo nulla quibusdam cum doloremque incidunt nemo sunt a tenetur omnis odio. </p>
							<hr>

							<form>
								<div class="top-margin">
									<label>First Name</label>
									<input type="text" class="form-control">
								</div>
								<div class="top-margin">
									<label>Last Name</label>
									<input type="text" class="form-control">
								</div>
								<div class="top-margin">
									<label>Email Address <span class="text-danger">*</span></label>
									<input type="text" class="form-control">
								</div>

								<div class="row top-margin">
									<div class="col-sm-6">
										<label>Password <span class="text-danger">*</span></label>
										<input type="text" class="form-control">
									</div>
									<div class="col-sm-6">
										<label>Confirm Password <span class="text-danger">*</span></label>
										<input type="text" class="form-control">
									</div>
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
										<label class="checkbox">
											<input type="checkbox"> 
											I've read the <a href="page_terms.html">Terms and Conditions</a>
										</label>                        
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Register</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
{%endblock%}	